name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo gha!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Correr Script
        run: python3 hola.py
